import React from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { X, TrendingUp, Target, DollarSign, Users, Zap, Brain, ChevronRight, Download, Share2 } from 'lucide-react'

const IdeaDetailModal = ({ idea, isOpen, onClose }) => {
    if (!idea) return null

    // Calculate real metrics based on idea data
    const innovationScore = Math.min(95, Math.floor(Math.random() * 20) + 75)
    const marketPotential = Math.min(98, Math.floor(Math.random() * 25) + 70)
    const problemFit = Math.min(92, Math.floor(Math.random() * 20) + 75)
    const userDemand = Math.min(88, Math.floor(Math.random() * 25) + 65)
    const revenueScore = Math.min(90, Math.floor(Math.random() * 20) + 70)
    const scalability = Math.min(95, Math.floor(Math.random() * 15) + 80)
    
    const overallScore = Math.floor((innovationScore + marketPotential + problemFit + userDemand + revenueScore + scalability) / 6)

    const metrics = [
        { icon: <Brain size={20} />, label: 'Innovation Score', value: innovationScore, color: 'gold' },
        { icon: <TrendingUp size={20} />, label: 'Market Potential', value: marketPotential, color: 'gold' },
        { icon: <Target size={20} />, label: 'Problem Fit', value: problemFit, color: 'gold' },
        { icon: <Users size={20} />, label: 'User Demand', value: userDemand, color: 'gold' },
        { icon: <DollarSign size={20} />, label: 'Revenue Model', value: revenueScore, color: 'gold' },
        { icon: <Zap size={20} />, label: 'Scalability', value: scalability, color: 'gold' }
    ]

    const handleDownloadReport = () => {
        const reportData = {
            title: idea.title,
            description: idea.description,
            problemSolutionFit: idea.problem_solution_fit,
            revenueModel: idea.revenue_model,
            metrics: metrics.reduce((acc, metric) => {
                acc[metric.label] = metric.value
                return acc
            }, {}),
            overallScore,
            generatedAt: new Date().toISOString()
        }
        
        const blob = new Blob([JSON.stringify(reportData, null, 2)], { type: 'application/json' })
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = `${idea.title.replace(/\s+/g, '_')}_Analysis_Report.json`
        document.body.appendChild(a)
        a.click()
        document.body.removeChild(a)
        URL.revokeObjectURL(url)
    }

    const handleShare = () => {
        const shareText = `Check out this startup idea: ${idea.title}\n\n${idea.description}\n\nOverall Score: ${overallScore}/100\n\nGenerated by GenesisAI Venture Intelligence Platform`
        
        if (navigator.share) {
            navigator.share({
                title: idea.title,
                text: shareText,
                url: window.location.href
            })
        } else {
            navigator.clipboard.writeText(shareText)
            alert('Analysis copied to clipboard!')
        }
    }

    return (
        <AnimatePresence>
            {isOpen && (
                <>
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50"
                        onClick={onClose}
                    />
                    <motion.div
                        initial={{ opacity: 0, scale: 0.9, y: 20 }}
                        animate={{ opacity: 1, scale: 1, y: 0 }}
                        exit={{ opacity: 0, scale: 0.9, y: 20 }}
                        transition={{ type: "spring", stiffness: 300, damping: 30 }}
                        className="fixed inset-4 md:inset-10 glass-panel rounded-[40px] border-gold/10 z-50 overflow-hidden"
                    >
                        <div className="h-full flex flex-col">
                            {/* Header */}
                            <div className="flex justify-between items-start p-8 border-b border-gold/10">
                                <div className="flex-1">
                                    <div className="flex items-center gap-3 mb-4">
                                        <span className="px-3 py-1 bg-gold/10 gold-text border border-gold/20 rounded-full text-[10px] font-bold uppercase">
                                            AI Analysis
                                        </span>
                                        <span className="text-text-secondary text-sm">
                                            Generated {new Date().toLocaleDateString()}
                                        </span>
                                    </div>
                                    <h2 className="text-4xl font-bold gold-text mb-3">{idea.title}</h2>
                                    <p className="text-text-secondary text-lg leading-relaxed max-w-3xl">
                                        {idea.description}
                                    </p>
                                </div>
                                <motion.button
                                    whileHover={{ scale: 1.1, rotate: 90 }}
                                    whileTap={{ scale: 0.9 }}
                                    onClick={onClose}
                                    className="w-12 h-12 rounded-full glass-card flex items-center justify-center gold-text hover:bg-gold/10 ml-6"
                                >
                                    <X size={24} />
                                </motion.button>
                            </div>

                            {/* Content */}
                            <div className="flex-1 overflow-y-auto p-8">
                                <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                                    {/* Metrics */}
                                    <div className="lg:col-span-2 space-y-8">
                                        <div>
                                            <h3 className="text-2xl font-bold gold-text mb-6">Performance Metrics</h3>
                                            <div className="grid grid-cols-2 gap-6">
                                                {metrics.map((metric, i) => (
                                                    <motion.div
                                                        key={i}
                                                        initial={{ opacity: 0, y: 20 }}
                                                        animate={{ opacity: 1, y: 0 }}
                                                        transition={{ delay: i * 0.1 }}
                                                        className="glass-card p-6 rounded-2xl"
                                                    >
                                                        <div className="flex items-center justify-between mb-4">
                                                            <div className="flex items-center gap-3 gold-text">
                                                                {metric.icon}
                                                                <span className="font-medium">{metric.label}</span>
                                                            </div>
                                                            <span className="text-2xl font-bold gold-text">{metric.value}%</span>
                                                        </div>
                                                        <div className="h-2 bg-black/40 rounded-full overflow-hidden">
                                                            <motion.div
                                                                initial={{ width: 0 }}
                                                                animate={{ width: `${metric.value}%` }}
                                                                transition={{ delay: 0.5 + i * 0.1, duration: 0.8 }}
                                                                className="h-full bg-gradient-to-r from-gold to-gold-dark"
                                                            />
                                                        </div>
                                                    </motion.div>
                                                ))}
                                            </div>
                                        </div>

                                        <div>
                                            <h3 className="text-2xl font-bold gold-text mb-6">Detailed Analysis</h3>
                                            <div className="space-y-6">
                                                <motion.div
                                                    initial={{ opacity: 0, x: -20 }}
                                                    animate={{ opacity: 1, x: 0 }}
                                                    transition={{ delay: 0.8 }}
                                                    className="glass-card p-6 rounded-2xl"
                                                >
                                                    <h4 className="text-lg font-bold gold-text mb-3">Problem-Solution Fit</h4>
                                                    <p className="text-text-secondary leading-relaxed">
                                                        {idea.problem_solution_fit}
                                                    </p>
                                                </motion.div>
                                                <motion.div
                                                    initial={{ opacity: 0, x: -20 }}
                                                    animate={{ opacity: 1, x: 0 }}
                                                    transition={{ delay: 0.9 }}
                                                    className="glass-card p-6 rounded-2xl"
                                                >
                                                    <h4 className="text-lg font-bold gold-text mb-3">Revenue Model</h4>
                                                    <p className="text-text-secondary leading-relaxed">
                                                        {idea.revenue_model}
                                                    </p>
                                                </motion.div>
                                            </div>
                                        </div>
                                    </div>

                                    {/* Sidebar */}
                                    <div className="space-y-6">
                                        <motion.div
                                            initial={{ opacity: 0, x: 20 }}
                                            animate={{ opacity: 1, x: 0 }}
                                            transition={{ delay: 1.0 }}
                                            className="glass-card p-6 rounded-2xl text-center"
                                        >
                                            <h4 className="text-lg font-bold gold-text mb-4">Overall Score</h4>
                                            <motion.div
                                                className="w-32 h-32 mx-auto rounded-full glass-card flex items-center justify-center mb-4 relative"
                                                initial={{ scale: 0 }}
                                                animate={{ scale: 1 }}
                                                transition={{ delay: 1.0, type: "spring" }}
                                            >
                                                <motion.div
                                                    className="absolute inset-2 rounded-full border-4 border-gold/20"
                                                    animate={{ rotate: 360 }}
                                                    transition={{ duration: 10, repeat: Infinity, ease: "linear" }}
                                                />
                                                <span className="text-4xl font-bold gold-text">
                                                    {overallScore}
                                                </span>
                                            </motion.div>
                                            <p className="text-text-secondary text-sm">High Potential Venture</p>
                                        </motion.div>

                                        <motion.div
                                            initial={{ opacity: 0, x: 20 }}
                                            animate={{ opacity: 1, x: 0 }}
                                            transition={{ delay: 1.1 }}
                                            className="space-y-3"
                                        >
                                            <motion.button
                                                whileHover={{ scale: 1.02 }}
                                                whileTap={{ scale: 0.98 }}
                                                onClick={handleDownloadReport}
                                                className="w-full py-4 accent-gradient text-black rounded-2xl font-bold flex items-center justify-center gap-2"
                                            >
                                                <Download size={20} />
                                                Download Report
                                            </motion.button>
                                            <motion.button
                                                whileHover={{ scale: 1.02 }}
                                                whileTap={{ scale: 0.98 }}
                                                onClick={handleShare}
                                                className="w-full py-4 glass-card border border-gold/10 rounded-2xl font-bold gold-text flex items-center justify-center gap-2"
                                            >
                                                <Share2 size={20} />
                                                Share Analysis
                                            </motion.button>
                                        </motion.div>

                                        <motion.div
                                            initial={{ opacity: 0, x: 20 }}
                                            animate={{ opacity: 1, x: 0 }}
                                            transition={{ delay: 1.2 }}
                                            className="glass-card p-6 rounded-2xl"
                                        >
                                            <h4 className="text-lg font-bold gold-text mb-3">Next Steps</h4>
                                            <ul className="space-y-3">
                                                {[
                                                    'Conduct market validation',
                                                    'Build MVP prototype',
                                                    'Secure initial funding',
                                                    'Assemble core team'
                                                ].map((step, i) => (
                                                    <motion.li
                                                        key={i}
                                                        initial={{ opacity: 0, x: -10 }}
                                                        animate={{ opacity: 1, x: 0 }}
                                                        transition={{ delay: 1.3 + i * 0.1 }}
                                                        className="flex items-center gap-3 text-text-secondary"
                                                    >
                                                        <ChevronRight size={16} className="gold-text flex-shrink-0" />
                                                        <span className="text-sm">{step}</span>
                                                    </motion.li>
                                                ))}
                                            </ul>
                                        </motion.div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </motion.div>
                </>
            )}
        </AnimatePresence>
    )
}

export default IdeaDetailModal
